Proper implementation of kernel weights
genn-team/genn pull request #478
Opened 2021-11-11 10:35 UTC by neworderofjamie

Previously, the way kernel weights were implemented was a bit of hack. You used procedural connectivity with a special variable initialisation snippet which pulled through the weights from an extra global parameter. This has a number of disadvantages:
* As the kernels are extra global parameters, GeNN has no idea how large they should be
* There's no way to support learning in this configuration as, from the point of view of the weight update model, the weights are produced by an opaque initialisation snippet.
* You can't take advantage of standard initialisation syntax for the kernels as they are extra global parameters.

This all stands in the way of both learning in convolutions and implementing a more efficient convolution implementation. This change hopefully solves all these problems via a new ``PROCEDURAL_KERNELG`` matrix mode. When this mode is used, all weight update model variables are allocated to the kernel size specified by the sparse connectivity initialisation model.

2021-11-16 14:38 UTC, tnowotny requested changes
Looking pretty good.
Probably better to correct the typo in the variable name (see comments).
What is the reason behind the empty files "skip_SingleThreadedCPU"?

2021-11-16 14:38 UTC, tnowotny commented on src/genn/backends/opencl/backend.cc
> +                               anyCustomUpdateInitGroups || anyCustomWUUpdateDenseInitGroups || anyDenseInitGroups || anyKerneInitGroups || anyConnectivityInitGroups || additionalParamsRequired);
should `anyKerneInitGroups` be `anyKernelInitGroups`?

2021-11-16 14:38 UTC, tnowotny commented on src/genn/backends/opencl/backend.cc
> +                               anyCustomWUUpdateDenseInitGroups || anyDenseInitGroups || anyKerneInitGroups || anyConnectivityInitGroups || additionalParamsRequired);
here, too

2021-11-16 14:38 UTC, tnowotny commented on src/genn/backends/opencl/backend.cc
> +                               anyDenseInitGroups || anyKerneInitGroups || anyConnectivityInitGroups || additionalParamsRequired);
and here ...

2021-11-16 15:16 UTC, neworderofjamie commented
So the ``skip_BACKEND_NAME`` files are just used to tell the test runner that this feature test shouldn't be run on a given backend e.g. single-threaded CPU doesn't support procedural connectivity and there's a few CUDA-specific tests as well

2021-11-17 20:03 UTC, tnowotny approved these changes
all good.

2021-11-18 09:23 UTC, merged